<?php

namespace App\Http\Controllers;

use App\Models\Account;
use App\Models\JournalVoucher;
use App\Models\Log;
use App\Models\Payment;
use App\Models\PaymentItem;
use App\Models\Supplier;
use App\Models\Transaction;
use Illuminate\Http\Request;

class PaymentController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('setup');
        $this->middleware('agreed');
        $this->middleware('accountant');
    }

    public function index()
    {
        $payments = Payment::select('id', 'payment_number', 'supplier_id', 'type', 'date', 'journal_voucher_id')->where('type', 'LIKE', 'payment')->filter()->orderBy('id', 'desc')->paginate(25);
        $suppliers = Supplier::select('id', 'name')->get();
        $data = compact('payments', 'suppliers');

        return view('payments.index', $data);
    }

    public function new()
    {
        $suppliers = Supplier::select('id', 'name')->get();
        $accounts = Account::select('id', 'account_number', 'account_description')->get();
        $data = compact('suppliers', 'accounts');

        return view('payments.new', $data);
    }

    public function create(Request $request)
    {
        $request->validate([
            'supplier_id' => 'required|exists:suppliers,id',
            'currency_id' => 'required|exists:currencies,id',
            'rate' => 'required|numeric',
            'foreign_currency_id' => 'required|exists:currencies,id',
            'description' => 'required|string',
            'date' => 'required|date',
            'account_id.*' => 'required|exists:accounts,id',
            'amount.*' => 'required|numeric',
        ]);

        $number = Payment::generate_number();

        $jv = JournalVoucher::create([
            'user_id' => auth()->user()->id,
            'currency_id' => $request->input('currency_id'),
            'foreign_currency_id' => $request->input('foreign_currency_id'),
            'rate' => $request->input('rate'),
            'date' => now(),
            'description' => 'Payment ' . $number . ', automatically generated by system...',
            'status' => 'unposted',
            'source' => 'system',
            'batch' => 'S',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $payment = Payment::create([
            'journal_voucher_id' => $jv->id,
            'payment_number' => $number,
            'supplier_id' => $request->supplier_id,
            'currency_id' => $request->currency_id,
            'foreign_currency_id' => $request->foreign_currency_id,
            'rate' => $request->rate,
            'type' => 'payment',
            'description' => $request->description,
            'date' => $request->date,
        ]);

        $total = 0;
        $rate = $request->rate;

        foreach ($request->input('account_id') as $key => $accountId) {
            $amount = $request->input('amount')[$key];
            $total += $amount;

            PaymentItem::create([
                'payment_id' => $payment->id,
                'account_id' => $accountId,
                'amount' => $amount,
            ]);

            // Account Credit transaction
            Transaction::create([
                'user_id' => auth()->user()->id,
                'journal_voucher_id' => $jv->id,
                'account_id' => $accountId,
                'currency_id' => $payment->currency_id,
                'debit' => 0,
                'credit' => $amount,
                'balance' => 0 - $amount,
                'foreign_currency_id' => $payment->foreign_currency_id,
                'rate' => $rate,
                'foreign_debit' => 0,
                'foreign_credit' => ($amount * $rate),
                'foreign_balance' => 0 - ($amount * $rate),
            ]);
        }

        // Supplier Debit transaction
        $supplier = Supplier::find($request->supplier_id);
        Transaction::create([
            'user_id' => auth()->user()->id,
            'journal_voucher_id' => $jv->id,
            'account_id' => $supplier->payable_account_id,
            'supplier_id' => $supplier->id,
            'currency_id' => $payment->currency_id,
            'debit' => $total,
            'credit' => 0,
            'balance' => $total,
            'foreign_currency_id' => $payment->foreign_currency_id,
            'rate' => $rate,
            'foreign_debit' => ($total * $rate),
            'foreign_credit' => 0,
            'foreign_balance' => ($total * $rate),
        ]);

        $text = ucwords(auth()->user()->name) . " created new Payment : " . $payment->payment_number . ", datetime :   " . now();
        Log::create(['text' => $text]);

        return redirect()->route('payments')->with('success', 'Payment created successfully!');
    }

    public function edit(Payment $payment)
    {
        if ($payment->can_edit()) {
            $accounts = Account::select('id', 'account_number', 'account_description')->get();

            $total = 0;
            foreach ($payment->payment_items as $item) {
                $total += $item->amount;
            }

            $data = compact('payment', 'accounts', 'total');
            return view('payments.edit', $data);
        } else {
            return redirect()->back()->with('Unable to edit...');
        }
    }

    public function update(Payment $payment, Request $request)
    {
        if ($payment->can_edit()) {
            $request->validate([
                'currency_id' => 'required|exists:currencies,id',
                'rate' => 'required|numeric',
                'foreign_currency_id' => 'required|exists:currencies,id',
                'description' => 'required|string',
                'date' => 'required|date',
            ]);

            $jv = $payment->journal_voucher;

            $payment->update([
                'currency_id' => $request->currency_id,
                'foreign_currency_id' => $request->foreign_currency_id,
                'rate' => $request->rate,
                'description' => $request->description,
                'date' => $request->date,
            ]);

            $total = 0;
            $rate = $request->rate;

            if ($request->input('account_id')[0] != null) {
                foreach ($request->input('account_id') as $key => $accountId) {
                    $amount = $request->input('amount')[$key];
                    $total += $amount;

                    PaymentItem::create([
                        'payment_id' => $payment->id,
                        'account_id' => $accountId,
                        'amount' => $amount,
                    ]);

                    // Account Credit transaction
                    Transaction::create([
                        'user_id' => auth()->user()->id,
                        'journal_voucher_id' => $jv->id,
                        'account_id' => $accountId,
                        'currency_id' => $payment->currency_id,
                        'debit' => 0,
                        'credit' => $amount,
                        'balance' => 0 - $amount,
                        'foreign_currency_id' => $payment->foreign_currency_id,
                        'rate' => $rate,
                        'foreign_debit' => 0,
                        'foreign_credit' => ($amount * $rate),
                        'foreign_balance' => 0 - ($amount * $rate),
                    ]);
                }
            }

            if ($total != 0) {
                // Debit transaction
                Transaction::create([
                    'user_id' => auth()->user()->id,
                    'journal_voucher_id' => $jv->id,
                    'account_id' => $payment->supplier->payable_account_id,
                    'supplier_id' => $payment->supplier_id,
                    'currency_id' => $payment->currency_id,
                    'debit' => $total,
                    'credit' => 0,
                    'balance' => $total,
                    'foreign_currency_id' => $payment->foreign_currency_id,
                    'rate' => $rate,
                    'foreign_debit' => ($total * $rate),
                    'foreign_credit' => 0,
                    'foreign_balance' => ($total * $rate),
                ]);
            }

            $text = ucwords(auth()->user()->name) . ' updated Payment ' . $payment->payment_number . ", datetime :   " . now();
            Log::create(['text' => $text]);

            return redirect()->back()->with('warning', 'Payment updated successfully!');
        } else {
            return redirect()->back()->with('Unable to edit...');
        }
    }

    public function show(Payment $payment)
    {
        $total = 0;
        $total_foreign = 0;

        foreach ($payment->payment_items as $item) {
            $total += $item->amount;
        }
        $total_foreign = $total * $payment->rate;

        $data = compact('payment', 'total', 'total_foreign');
        return view('payments.show', $data);
    }

    public function Return(Payment $payment)
    {
        $payments = Payment::select('id', 'payment_number')->where('type', 'payment')->get();
        return view('payments.return', compact('payment', 'payments'));
    }

    public function ReturnSave(Request $request)
    {
        $request->validate([
            'payment_id' => 'required',
            'items' => 'required|array',
        ]);

        $old_payment = Payment::find($request->input('payment_id'));
        $return_number = Payment::generate_return_number();

        $jv = JournalVoucher::create([
            'user_id' => auth()->user()->id,
            'currency_id' => $old_payment->currency_id,
            'foreign_currency_id' => $old_payment->foreign_currency_id,
            'rate' => $old_payment->rate,
            'date' => date('Y-m-d'),
            'description' => 'Return Payment for ' . $old_payment->payment_number . ', automatically generated by system...',
            'status' => 'unposted',
            'source' => 'system',
            'batch' => 'S',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $payment = Payment::create([
            'journal_voucher_id' => $jv->id,
            'payment_number' => $return_number,
            'supplier_id' => $old_payment->supplier_id,
            'currency_id' => $old_payment->currency_id,
            'foreign_currency_id' => $old_payment->foreign_currency_id,
            'rate' => $old_payment->rate,
            'type' => 'return ' . $old_payment->type,
            'description' => $old_payment->description,
            'date' => date('Y-m-d'),
        ]);

        $total = 0;
        $rate = $old_payment->rate;

        foreach ($request->items as $index => $item) {
            if (isset($item['id'])) {
                $old_account = PaymentItem::find($item['id'])->account;
                $amount = $item['quantity'];

                PaymentItem::create([
                    'payment_id' => $payment->id,
                    'account_id' => $old_account->id,
                    'amount' => $amount,
                ]);

                // Account Credit transaction
                Transaction::create([
                    'user_id' => auth()->user()->id,
                    'journal_voucher_id' => $jv->id,
                    'account_id' => $old_account->id,
                    'currency_id' => $payment->currency_id,
                    'debit' => 0,
                    'credit' => $amount,
                    'balance' => 0 - $amount,
                    'foreign_currency_id' => $payment->foreign_currency_id,
                    'rate' => $rate,
                    'foreign_debit' => 0,
                    'foreign_credit' => ($amount * $rate),
                    'foreign_balance' => 0 - ($amount * $rate),
                ]);

                $total += $amount;
            }
        }

        // Debit transaction
        Transaction::create([
            'user_id' => auth()->user()->id,
            'journal_voucher_id' => $jv->id,
            'account_id' => $old_payment->supplier->payable_account_id,
            'supplier_id' => $old_payment->supplier_id,
            'currency_id' => $payment->currency_id,
            'debit' => $total,
            'credit' => 0,
            'balance' => $total,
            'foreign_currency_id' => $payment->foreign_currency_id,
            'rate' => $rate,
            'foreign_debit' => ($total * $rate),
            'foreign_credit' => 0,
            'foreign_balance' => ($total * $rate),
        ]);

        Log::create([
            'text' => ucwords(auth()->user()->name) . ' Returned Payment ' . $payment->payment_number . ", datetime :   " . now(),
        ]);

        return redirect()->route('payments')->with('success', 'Payment Returned successfully!');
    }

    public function items(Payment $payment)
    {
        $items = $payment->payment_items;

        $customizedItems = [];
        $index = 0;
        foreach ($items as $item) {
            $customizedItem = [
                'id' => $item->id,
                'name' => $item->account->account_number,
                'quantity' => $item->amount,
            ];
            $customizedItems[] = $customizedItem;
            $index++;
        }

        return response()->json($customizedItems);
    }

    public function destroy(Payment $payment)
    {
        if ($payment->can_delete()) {
            $text = ucwords(auth()->user()->name) . " deleted Payment : " . $payment->payment_number . ", datetime :   " . now();

            Log::create(['text' => $text]);
            $payment->delete();

            return redirect()->back()->with('error', 'Payment deleted successfully!');
        } else {
            return redirect()->back()->with('error', 'Unothorized Access...');
        }
    }
}
