<?php

namespace App\Http\Controllers;

use App\Models\Account;
use App\Models\Item;
use App\Models\JournalVoucher;
use App\Models\Log;
use App\Models\Receipt;
use App\Models\ReceiptItem;
use App\Models\Supplier;
use App\Models\Tax;
use App\Models\Transaction;
use App\Models\Variable;
use Illuminate\Http\Request;

class ReceiptController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:receipts.read')->only('index');
        $this->middleware('permission:receipts.create')->only(['new', 'create']);
        $this->middleware('permission:receipts.update')->only(['edit', 'update']);
        $this->middleware('permission:receipts.delete')->only('destroy');
        $this->middleware('permission:receipts.export')->only('export');
    }

    public function index()
    {
        $receipts = Receipt::select('id', 'receipt_number', 'supplier_invoice', 'date', 'supplier_id', 'tax_id', 'currency_id', 'foreign_currency_id', 'journal_voucher_id')->filter()->orderBy('id', 'desc')->paginate(25);
        $suppliers = Supplier::select('id', 'name')->get();
        $taxes = Tax::select('id', 'name')->get();

        $data = compact('receipts', 'suppliers', 'taxes');
        return view('receipts.index', $data);
    }

    public function new()
    {
        $items = Item::select('id', 'name', 'unit_price', 'unit', 'type')->where('type', 'expense')->get();
        $taxes = Tax::select('id', 'name', 'rate')->get();
        $suppliers = Supplier::select('id', 'name')->get();
        $data = compact('suppliers', 'items', 'taxes');

        return view('receipts.new', $data);
    }

    public function create(Request $request)
    {
        $validatedData = $request->validate([
            'supplier_id' => 'required|exists:suppliers,id',
            'supplier_invoice' => 'required|string|max:255|unique:receipts',
            'tax_id' => 'required|exists:taxes,id',
            'currency_id' => 'required|exists:currencies,id',
            'foreign_currency_id' => 'required|exists:currencies,id',
            'rate' => 'required|numeric|min:0',
            'date' => 'required|date',
            'item_id.*' => 'required|exists:items,id',
            'quantity.*' => 'required|numeric|min:1',
            'unit_cost.*' => 'required|numeric|min:0',
        ]);

        $number = Receipt::generate_number();
        $rate = $validatedData['rate'];
        $taxRate = Tax::findOrFail($validatedData['tax_id'])->rate / 100;

        // Create Journal Voucher
        $jv = JournalVoucher::create([
            'user_id' => auth()->id(),
            'currency_id' => $validatedData['currency_id'],
            'foreign_currency_id' => $validatedData['foreign_currency_id'],
            'rate' => $rate,
            'date' => $validatedData['date'],
            'description' => "Receipt $number, automatically generated by system",
            'status' => 'unposted',
            'source' => 'system',
            'batch' => 'S',
        ]);

        // Create Receipt
        $receipt = Receipt::create([
            'receipt_number' => $number,
            'supplier_invoice' => $validatedData['supplier_invoice'],
            'supplier_id' => $validatedData['supplier_id'],
            'tax_id' => $validatedData['tax_id'],
            'currency_id' => $validatedData['currency_id'],
            'foreign_currency_id' => $validatedData['foreign_currency_id'],
            'rate' => $rate,
            'journal_voucher_id' => $jv->id,
            'date' => $validatedData['date'],
            'purchase_order_id' => $validatedData['purchase_order_id'] ?? null,
            'type' => 'receipt',
        ]);

        $totalItemCost = 0;
        $totalTax = 0;

        foreach ($validatedData['item_id'] as $key => $itemId) {
            $quantity = $validatedData['quantity'][$key];
            $unitCost = $validatedData['unit_cost'][$key];
            $totalCost = $unitCost * $quantity;
            $vat = $totalCost * $taxRate;

            ReceiptItem::create([
                'receipt_id' => $receipt->id,
                'item_id' => $itemId,
                'quantity' => $quantity,
                'unit_cost' => $unitCost,
                'total_cost' => $totalCost,
                'vat' => $vat,
                'rate' => $rate,
                'total_cost_after_vat' => $totalCost + $vat,
                'total_foreign_cost' => $totalCost * $rate,
            ]);

            $totalItemCost += $totalCost;
            $totalTax += $vat;
        }

        $totalCostAfterVAT = $totalItemCost + $totalTax;

        // Expense Debit
        $expenseAccount = Account::findOrFail(Variable::where('title', 'expense_account')->first()->value);
        $this->createTransaction($jv, $expenseAccount->id, $totalCostAfterVAT - $totalTax, 0, $rate, $receipt);

        // Tax Debit
        $taxAccount = Tax::findOrFail($validatedData['tax_id'])->account;
        $this->createTransaction($jv, $taxAccount->id, $totalTax, 0, $rate, $receipt);

        // Supplier Credit
        $supplier = Supplier::findOrFail($validatedData['supplier_id']);
        $this->createTransaction(
            $jv,
            $supplier->payable_account_id,
            0,
            $totalCostAfterVAT,
            $rate,
            $receipt,
            $supplier->id
        );

        Log::create(['text' => ucwords(auth()->user()->name) . " created new Receipt: " . $receipt->receipt_number . ", datetime: " . now()]);

        return redirect()->route('receipts')->with('success', 'Receipt created successfully!');
    }

    public function edit(Receipt $receipt)
    {
        $items = Item::select('id', 'name')->where('type', 'expense')->get();
        $taxes = Tax::select('id', 'name', 'rate')->get();
        $suppliers = Supplier::select('id', 'name')->get();

        $total = 0;
        $total_foreign = 0;
        $total_after_tax = 0;
        $total_tax = 0;

        foreach ($receipt->receipt_items as $item) {
            $total += $item->total_cost;
            $total_tax += $item->vat;
            $total_foreign += $item->total_foreign_cost;
            $total_after_tax += $item->total_cost_after_vat;
        }

        $data = compact('receipt', 'items', 'taxes', 'suppliers', 'total', 'total_foreign', 'total_after_tax', 'total_tax');

        return view('receipts.edit', $data);
    }

    public function update(Receipt $receipt, Request $request)
    {
        $validatedData = $request->validate([
            'supplier_id' => 'required|exists:suppliers,id',
            'supplier_invoice' => 'required|string|max:255|unique:receipts,supplier_invoice,' . $receipt->id,
            'tax_id' => 'required|exists:taxes,id',
            'currency_id' => 'required|exists:currencies,id',
            'foreign_currency_id' => 'required|exists:currencies,id',
            'rate' => 'required|numeric|min:0',
            'date' => 'required|date',
            'item_id.*' => 'required|exists:items,id',
            'quantity.*' => 'required|numeric|min:1',
            'unit_cost.*' => 'required|numeric|min:0',
        ]);

        $jv = $receipt->journal_voucher;

        $receipt->update([
            'supplier_invoice' => $request->input('supplier_invoice'),
            'tax_id' => $request->input('tax_id'),
            'currency_id' => $request->input('currency_id'),
            'foreign_currency_id' => $request->input('foreign_currency_id'),
            'date' => $request->input('date'),
        ]);

        $totalItemCost = 0;
        $totalTax = 0;
        $rate = $validatedData['rate'];
        $taxRate = Tax::findOrFail($validatedData['tax_id'])->rate / 100;

        // Create new receipt items
        foreach ($validatedData['item_id'] as $key => $itemId) {
            $quantity = $validatedData['quantity'][$key];
            $unitCost = $validatedData['unit_cost'][$key];
            $totalCost = $unitCost * $quantity;
            $vat = $totalCost * $taxRate;

            ReceiptItem::create([
                'receipt_id' => $receipt->id,
                'item_id' => $itemId,
                'quantity' => $quantity,
                'unit_cost' => $unitCost,
                'total_cost' => $totalCost,
                'vat' => $vat,
                'rate' => $rate,
                'total_cost_after_vat' => $totalCost + $vat,
                'total_foreign_cost' => $totalCost * $rate,
            ]);

            $totalItemCost += $totalCost;
            $totalTax += $vat;
        }

        $totalCostAfterVAT = $totalItemCost + $totalTax;

        // Expense Debit
        $expenseAccount = Account::findOrFail(Variable::where('title', 'expense_account')->first()->value);
        $this->createTransaction($receipt->journal_voucher, $expenseAccount->id, $totalCostAfterVAT - $totalTax, 0, $rate, $receipt);

        // Tax Debit
        $taxAccount = Tax::findOrFail($validatedData['tax_id'])->account;
        $this->createTransaction($receipt->journal_voucher, $taxAccount->id, $totalTax, 0, $rate, $receipt);

        // Supplier Credit
        $supplier = Supplier::findOrFail($validatedData['supplier_id']);
        $this->createTransaction(
            $receipt->journal_voucher,
            $supplier->payable_account_id,
            0,
            $totalCostAfterVAT,
            $rate,
            $receipt,
            $supplier->id
        );

        $text = ucwords(auth()->user()->name) . ' updated Receipt ' . $receipt->receipt_number . ", datetime :   " . now();
        Log::create(['text' => $text]);

        return redirect()->back()->with('warning', 'Receipt updated successfully!');
    }

    public function show(Receipt $receipt)
    {
        $total = 0;
        $total_tax = 0;
        $total_foreign = 0;
        $total_after_tax = 0;

        foreach ($receipt->receipt_items as $item) {
            $total += $item->total_cost;
            $total_tax += $item->vat;
            $total_foreign += $item->total_foreign_cost;
            $total_after_tax += $item->total_cost_after_vat;
        }

        $data = compact('receipt', 'total', 'total_tax', 'total_foreign', 'total_after_tax');
        return view('receipts.show', $data);
    }

    public function Return(Receipt $receipt)
    {
        $receipts = Receipt::select('id', 'receipt_number')->where('type', 'receipt')->get();
        return view('receipts.return', compact('receipt', 'receipts'));
    }

    public function ReturnSave(Request $request)
    {
        $request->validate([
            'receipt_id' => 'required',
            'items' => 'required|array',
        ]);

        $old_receipt = Receipt::find($request->input('receipt_id'));
        $return_number = Receipt::generate_return_number();

        // create automatic JV
        $jv = JournalVoucher::create([
            'user_id' => auth()->user()->id,
            'currency_id' => $old_receipt->currency_id,
            'foreign_currency_id' => $old_receipt->foreign_currency_id,
            'rate' => $old_receipt->rate,
            'date' => date('Y-m-d'),
            'description' => 'Return Receipt for ' . $old_receipt->receipt_number . ', automatically generated by system...',
            'status' => 'unposted',
            'source' => 'system',
            'batch' => 'S',
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $receipt = Receipt::create([
            'journal_voucher_id' => $jv->id,
            'receipt_number' => $return_number,
            'supplier_id' => $old_receipt->supplier_id,
            'supplier_invoice' => $old_receipt->supplier_invoice,
            'tax_id' => $old_receipt->tax_id,
            'currency_id' => $old_receipt->currency_id,
            'foreign_currency_id' => $old_receipt->foreign_currency_id,
            'rate' => $old_receipt->rate,
            'date' => date('Y-m-d'),
            'type' => 'return',
        ]);

        $total = 0;
        $total_lc = 0;
        $total_tax = 0;
        $total_landed_cost = 0;
        $rate = $old_receipt->rate ?? 0;

        // create landed cost and get total
        foreach ($request->landed_costs as $index => $lc) {
            if (isset($lc['id'])) {
                $old_lc = LandedCost::find($lc['id']);

                LandedCost::create([
                    'receipt_id' => $receipt->id,
                    'name' => $old_lc->name,
                    'supplier_id' => $old_lc->supplier_id,
                    'currency_id' => $old_lc->currency_id,
                    'amount' => $lc['amount'],
                    'rate' => $rate,
                    'date' => $old_lc->date,
                ]);

                // create landed cost supplier credit transaction
                $old_lc_supplier = $old_lc->supplier;
                Transaction::create([
                    'user_id' => auth()->user()->id,
                    'journal_voucher_id' => $jv->id,
                    'account_id' => $old_lc_supplier->payable_account_id,
                    'supplier_id' => $old_lc_supplier->id,
                    'currency_id' => $receipt->currency_id,
                    'debit' => $lc['amount'],
                    'credit' => 0,
                    'balance' => $lc['amount'],
                    'foreign_currency_id' => $receipt->foreign_currency_id,
                    'rate' => $rate,
                    'foreign_debit' => $lc['amount'] * $rate,
                    'foreign_credit' => 0,
                    'foreign_balance' => $lc['amount'] * $rate,
                ]);

                $total_landed_cost += $lc['amount'];
            }
        }

        $tax_rate = $old_receipt->tax->rate / 100;
        foreach ($request->items as $index => $item) {
            if (isset($item['id'])) {
                $old_receipt_item = ReceiptItem::find($item['id']);
                $original_unit_cost = $old_receipt_item->unit_cost;
                $t = $original_unit_cost * $item['quantity'];
                $total += $t;

                $vat = $t * $tax_rate;
                $total_tax += $vat;
            }
        }

        foreach ($request->items as $index => $item) {
            if (isset($item['id'])) {
                $old_receipt_item = ReceiptItem::find($item['id']);
                $original_unit_cost = $old_receipt_item->unit_cost;
                $t = $original_unit_cost * $item['quantity'];

                $vat = $t * $tax_rate;
                $total_cost_after_vat = $t + $vat;

                $landed_cost_per_item = ($original_unit_cost / $total) * $total_landed_cost;

                $total_after_landed_cost = $t + $landed_cost_per_item;
                $total_lc += ($total_after_landed_cost - $vat);
                $unit_cost = $total_after_landed_cost / $item['quantity'];

                ReceiptItem::create([
                    'receipt_id' => $receipt->id,
                    'item_id' => $old_receipt_item->item_id,
                    'quantity' => $item['quantity'],
                    'unit_cost' => $original_unit_cost,
                    'total_cost' => $t,
                    'vat' => $vat,
                    'rate' => $rate,
                    'total_cost_after_vat' => $total_cost_after_vat,
                    'total_after_landed_cost' => $total_after_landed_cost,
                    'total_foreign_cost' => $t * $rate,
                ]);


                $old_receipt_item->item->update_unit_cost($unit_cost);
            }
        }

        // create inventory credit transaction
        $inventory_account = $old_receipt_item->item->inventory_account;
        Transaction::create([
            'user_id' => auth()->user()->id,
            'journal_voucher_id' => $jv->id,
            'account_id' => $inventory_account->id,
            'currency_id' => $receipt->currency_id,
            'debit' => 0,
            'credit' => $total_lc,
            'balance' => 0 - $total_lc,
            'foreign_currency_id' => $receipt->foreign_currency_id,
            'rate' => $rate,
            'foreign_debit' => 0,
            'foreign_credit' => $total_lc * $rate,
            'foreign_balance' => 0 - ($total_lc * $rate),
        ]);

        // create tax credit transaction
        $account = $old_receipt->tax->account;
        Transaction::create([
            'user_id' => auth()->user()->id,
            'journal_voucher_id' => $jv->id,
            'account_id' => $account->id,
            'currency_id' => $receipt->currency_id,
            'debit' => 0,
            'credit' => $total_tax,
            'balance' => 0 - $total_tax,
            'foreign_currency_id' => $receipt->foreign_currency_id,
            'rate' => $rate,
            'foreign_debit' => 0,
            'foreign_credit' => $total_tax * $rate,
            'foreign_balance' => 0 - ($total_tax * $rate),
        ]);

        // create supplier credit transaction
        $supplier = $old_receipt->supplier;
        Transaction::create([
            'user_id' => auth()->user()->id,
            'journal_voucher_id' => $jv->id,
            'account_id' => $supplier->payable_account_id,
            'supplier_id' => $supplier->id,
            'currency_id' => $receipt->currency_id,
            'debit' => $total_lc + $total_tax - $total_landed_cost,
            'credit' => 0,
            'balance' => $total_lc + $total_tax - $total_landed_cost,
            'foreign_currency_id' => $receipt->foreign_currency_id,
            'rate' => $rate,
            'foreign_debit' => ($total_lc + $total_tax - $total_landed_cost) * $rate,
            'foreign_credit' => 0,
            'foreign_balance' => ($total_lc + $total_tax - $total_landed_cost) * $rate,
        ]);

        Log::create([
            'text' => ucwords(auth()->user()->name) . ' Returned Receipts ' . $receipt->receipt_number . ", datetime :   " . now(),
        ]);

        return redirect()->route('receipts')->with('success', 'Receipts Returned successfully!');
    }

    public function items(Receipt $receipt)
    {
        $items = $receipt->receipt_items;

        $customizedItems = [];
        $index = 0;
        foreach ($items as $item) {
            $customizedItem = [
                'id' => $item->id,
                'name' => $item->item->itemcode,
                'quantity' => $item->quantity,
            ];
            $customizedItems[] = $customizedItem;
            $index++;
        }

        return response()->json($customizedItems);
    }

    public function landed_costs(Receipt $receipt)
    {
        $lcs = $receipt->landed_costs;

        $customizedResult = [];
        $index = 0;
        foreach ($lcs as $lc) {
            $customizedResult = [
                'id' => $lc->id,
                'name' => $lc->name,
                'amount' => $lc->amount,
            ];
            $customizedResults[] = $customizedResult;
            $index++;
        }

        return response()->json($customizedResults);
    }

    public function destroy(Receipt $receipt)
    {
        if ($receipt->can_delete()) {
            $text = ucwords(auth()->user()->name) . " deleted Receipt : " . $receipt->receipt_number . ", datetime :   " . now();

            Log::create(['text' => $text]);
            $receipt->delete();

            return redirect()->back()->with('error', 'Receipt deleted successfully!');
        } else {
            return redirect()->back()->with('error', 'Unothorized Access...');
        }
    }

    // -------------------
    // Private
    // -------------------
    private function createTransaction($jv, $accountId, $debit, $credit, $rate, $receipt, $supplierId = null)
    {
        Transaction::create([
            'user_id' => auth()->id(),
            'journal_voucher_id' => $jv->id,
            'account_id' => $accountId,
            'supplier_id' => $supplierId,
            'currency_id' => $receipt->currency_id,
            'debit' => $debit,
            'credit' => $credit,
            'balance' => $debit - $credit,
            'foreign_currency_id' => $receipt->foreign_currency_id,
            'rate' => $rate,
            'foreign_debit' => $debit * $rate,
            'foreign_credit' => $credit * $rate,
            'foreign_balance' => ($debit - $credit) * $rate,
        ]);
    }
}
